### ISSUE TITLE
Dark version

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#12]
I think assigning colors to different areas and buttons is not that difficult, but it will greatly improve the perception of the program. Right now it literally has no design at all, which can make it look unfinished. And the bright white background is not very pleasing to the eye.
 Of course, in addition to the main screen, you need to paint all the other screens. Setting, pictures, variables, etc.

![Pasted image 20230131194846](https://user-images.githubusercontent.com/123765425/216001020-93349c62-cde3-4e79-8d88-565a87add437.png)
![Pasted image 20230131194903](https://user-images.githubusercontent.com/123765425/216001042-b8f79f14-0942-4d33-b354-19497d899d5a.png)

**Comment by n7484443** [comment]
Added a0f9f82dedd0fdc572051825684a0f6c8499be6e
