### ISSUE TITLE
Replace the sliders with buttons.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#17]
Replace the sliders with buttons. Right now they are very large and attract too much attention. But if you make them smaller and without bright colors, they will probably become awkward. A regular gray button with a check mark would be much better.

![image](https://user-images.githubusercontent.com/123765425/216012720-383f0045-695e-4720-894d-224f5aa00e14.png)

Or at least something like that, especially since the button is the entire inscription "Hidden variables" and it's hard to miss here.
![image](https://user-images.githubusercontent.com/123765425/216031928-c53fa249-c6f5-4d24-a997-3abf66efe31e.png)

**Comment by n7484443** [comment]
Fix b9e2f90501501ef50086d584d61ebbab4b44f332
