### ISSUE TITLE
Move the sliders in the settings window. 

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#18]
Now they are arranged in a very strange way. 
It would be better to place them to the left of the description and indent them slightly to the next slider. 
Or it would be better to redesign this menu completely -_-
 
![image](https://user-images.githubusercontent.com/123765425/216015627-807cbe37-8d84-4aac-a662-ce092515d52f.png)

**Comment by DragonsWho** [comment]
Possible fast improvement

![image](https://user-images.githubusercontent.com/123765425/216034022-1f49cdc7-8f77-4110-8b14-44dff8733d5c.png)

But then again, sliders look good when the settings are vertical, and they are in a straight row... Not like this.

**Comment by n7484443** [comment]
![image](https://user-images.githubusercontent.com/7384324/217604364-8a7d342d-135b-42e7-a6bd-182dd2a7bbab.png)
fix af66d3e3300cf154001f5f3feeae2cf029a2c5b0
