### ISSUE TITLE
Do not shuffle variables!

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#19]
During any editing, even if you just open the settings menu and leave it immediately, the variable moves to the bottom right corner, which is very annoying! They should be fixed in place, just like the choices! The user should not have to look for the variable he wants every time, it's not mahjong!

Ideally, they should be dragged from place to place with the mouse.  Just like the choices.
Even better is to split the menu horizontally into two parts. The upper part shows the variables that will be visible to the player, and the lower part shows all the others, so they are not in the way and do not distract. And all new variables should be invisible by default

![image](https://user-images.githubusercontent.com/123765425/216016527-258c3892-8dbe-45c5-a8b0-94682b4a33fb.png)

![image](https://user-images.githubusercontent.com/123765425/216018680-6e3d8002-8a8e-44b3-88ec-49679d3e97de.png)

**Comment by n7484443** [comment]
Fix with drag-drop 6f0dbc52d74b64b8d34f4bc03354239149496e27
It will be merged next minor patch
