### ISSUE TITLE
Re-editing an image.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#20]
Now, if you cropped something wrong, you have to delete the image, upload it again, and try again. And if you wanted just a little bit less height, then you have to guess again, because the previous image is gone. It's very frustrating.

Also, CYOAP doesn't allow you to load the same image twice. If I want to crop and do the head and legs separately, I have to make a copy on my hard drive first.

**Comment by n7484443** [comment]
Add feature 5a504de86b52c11a8c7313bcadafd3d702f32e41
