### ISSUE TITLE
Clear button boundaries.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#22]
Right now there is a VERY strange shaped button on the home screen. What's more, it completely blends in with the background. And yes, you can even click it at the bottom, even though there are literally a few pixels there.

How is it now.
![image](https://user-images.githubusercontent.com/123765425/216022249-33b2daa6-5609-49dd-8505-81e58e170284.png)
![image](https://user-images.githubusercontent.com/123765425/216022073-d7dd17d1-4530-4d54-8c8c-e248f4147df7.png)

How can it be.
1.
![image](https://user-images.githubusercontent.com/123765425/216023276-7b666f0d-c8ee-43dd-8904-22609e94d028.png)
2. 
![image](https://user-images.githubusercontent.com/123765425/216025107-1b1be40f-86b6-44a9-a205-19ee6e130444.png)

**Comment by n7484443** [comment]
Fix 5d2d6958bd23d8ce2accc078fa71540f7f526936
