### ISSUE TITLE
General background color.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#23]
Now the user can only change the background color of individual rows, which leaves the bottom of the CYOA white. 
This is bad.
The user should be able to set the background color around the Summary button. As well as the appearance of the button itself, so that it doesn't stand out from the rest of the game.
![image](https://user-images.githubusercontent.com/123765425/216059017-664e1242-250f-44bf-ba11-191728702184.png)

I have not checked, but if there is a white stripe at the top for these buttons, its background should also match the background of the CYOA
![image](https://user-images.githubusercontent.com/123765425/216060614-2ec0785c-571a-4675-83e5-9e5a59c3e5d7.png)

**Comment by n7484443** [comment]
Fix
