### ISSUE TITLE
Ability to renaming row.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#29]
Since one of the features of cyoap is the sidebar with the ability to quickly navigate, the ability to change the names of the rows is absolutely necessary.
![image](https://user-images.githubusercontent.com/123765425/216070528-b1621673-2609-454d-a451-d904f2183b04.png)
 
![image](https://user-images.githubusercontent.com/123765425/216072570-0ae32b59-f980-4f78-a2ed-bb54afbeac3c.png)

**Comment by DragonsWho** [comment]
You should also display this name in the main menu. There is an empty space there anyway.

![image](https://user-images.githubusercontent.com/123765425/216094501-a00c0c92-969c-4c0d-b5a3-e63aab580c35.png)

**Comment by n7484443** [comment]
Fix fdb2b2e4a505c721f96bd52a20b891470ca1176b 5a0106a7d32281652c755c3e18f1abf6cc92ef43
