### ISSUE TITLE
Adding new image

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#31]
The button in the lower right corner is too pale and bland. I still sometimes get lost and spend a second trying to figure out how to add an image.

![image](https://user-images.githubusercontent.com/123765425/216077657-cfca6b0d-7863-416b-a522-8edea78cdc75.png)

**Comment by n7484443** [comment]
Fix 9acbd7f33ce1869f5c3621180fb13005f81322cc
