### ISSUE TITLE
Remove this blur. At the top and at the bottom. 

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#34]
It has no practical sense and hides quite a large part of the screen. 
If you want to make it obvious that there is something at the top and bottom - you could at least make it three times smaller and more transparent. Although it seems to me that on all the other sites people somehow manage without it.

![image](https://user-images.githubusercontent.com/123765425/216082583-e799c288-458b-4f26-95d1-1175a3a11c54.png)

**Comment by n7484443** [comment]
Fix - c208a5feeee7b618cd076ea38f7b6f45ced569bb
