### ISSUE TITLE
Put the arrows on the row together. 

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#35]
Put the arrows on the row together. On the right side. 
Placing the controls so far apart is very illogical. They should all be uniformly placed on the choices and on the row.

![image](https://user-images.githubusercontent.com/123765425/216087079-1d72a9de-3b6a-4cd3-8018-fe41fb5872f1.png)

**Comment by n7484443** [comment]
Fix 787a0cabdac86ff1fc0158b0ee1b8ccf32079cc8
