### ISSUE TITLE
Open choices through the left panel, when you are in edit mode.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#37]
It should be possible to open options from the left pane when you are in edit mode. Now you have to go back to the main screen first to do this. This greatly reduces the usefulness of the left pane.

![image](https://user-images.githubusercontent.com/123765425/216092869-dbc2645c-e34e-47e5-b4b2-8e6718d5f88b.png)

**Comment by n7484443** [comment]
Fix 3.9.0
