### ISSUE TITLE
Change the default visibility state of the variable to the opposite.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#38]
'variable_show': 'Show when playing', -> "Hide completely"

Change the default state to the opposite. CYOAP has an advantage over ICC in the form of normally working conditions. Accordingly, it is likely that there will be more variables in the game than points displayed to the player. 

![image](https://user-images.githubusercontent.com/123765425/216096033-d845bf1a-4af3-44a8-8e70-a49a79e5fba6.png)

**Comment by n7484443** [comment]
Fix be2b93e58ffc106013497b094f20566da520b53b
