### ISSUE TITLE
Align "Variable name" with everything else. 

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#39]
Align "Variable name" with everything else. Dynamic text is nice, but here it's just confusing. To make it less work, you can just enter the default value. It's the same as Id anyway.

![image](https://user-images.githubusercontent.com/123765425/216096916-de0ddf5e-0c67-4b4d-9046-1291fa002286.png)

![image](https://user-images.githubusercontent.com/123765425/216098870-bfe0a332-9e3d-45a7-8dd6-be3404725f6a.png)

**Comment by n7484443** [comment]
Fixed it on version 4.4.1 by refactoring variable tab
