### ISSUE TITLE
imageSource 오류

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_flutter#43]
![N1](https://user-images.githubusercontent.com/125365947/218732746-e2b026b9-00e9-45c5-8aa4-248001b32cc9.PNG)

위와 같이 여러 파일에서 서로 다른 CYOA를 제작할 경우 발생하는 오류입니다.

일반적으로 하나의 작업물에만 들어갔을 경우 문제 발생은 없습니다.

![N4](https://user-images.githubusercontent.com/125365947/218733431-32ab04d2-9fde-42fe-8445-1ccaa8359742.PNG)
![N2](https://user-images.githubusercontent.com/125365947/218733454-3dbbb76b-e4fd-4f4b-a100-589deb5fadc9.PNG)
>해당 작업물에 하나의 사진과 하나의 위치가 지정된 모습 figure 1

그러나 다른 작업물에 들어갔다가 나올 경우 문제가 발생합니다.

![N3](https://user-images.githubusercontent.com/125365947/218733674-95241373-3457-42da-b8b1-abf90f6385e5.PNG)
>문제 발생 시 imageSource 파일 figure 2

우선 A가 사진 하나 뿐인 제작물
B가 잠시 열람한 제작물
열람하지도 않았으나 존재하는 제작물을 C라고 지칭하겠습니다.

한 번의 프로그램 실행 시 A에만 들어가 저장하였을 경우 정상적으로 하나의 사진만 저장됩니다. (figure 1)

하나, 실행 시 A와 B 열람 후 A에서 저장하기를 누를 경우 해당 제작물이 아닌 사진까지 지정이 됩니다. (figure 2)
그러나 제작 시 이미지 탭 내부에서 발견되는 문제는 없고 단순히 imagesource 문서 내부에서만 보이는 문제입니다.
여기서 위치 지정이 되는 사진은 A와 B 뿐만 아니라 C의 사진까지 지정됩니다.

**Comment by n7484443** [comment]
수정 09e9f6e354a9fc9b52d5577a752bcca478b21d73
다만 기존의 문제되던 파일은 고쳐지지는 않습니다. 삭제하거나 수정해야 할 듯 합니다.
