### ISSUE TITLE
Title of new choices. Its not changed.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#45]
Issue closed, but... Um... Nothing has changed. 

![image](https://user-images.githubusercontent.com/123765425/219964071-793ebfa4-4e41-458b-a719-ac6b1cad996a.png)
![image](https://user-images.githubusercontent.com/123765425/219964164-1caa72cd-4685-4a6d-b5b5-24e154e0a850.png)

**Comment by n7484443** [comment]
Currently it not merged to main branch. next minor or major update contains that.
