### ISSUE TITLE
Deleting a Row.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#47]
After deleting the last selection, the line itself does not disappear, but remains an empty line. If you save, quit, and load again, it will still disappear, but this is clearly not how it should ideally work.

![image](https://user-images.githubusercontent.com/123765425/219965946-d8b151c4-060a-4549-b68b-dcc421bac5a6.png)

**Comment by n7484443** [comment]
fixed v4.4.8
