### ISSUE TITLE
프리셋 상세 설정 연동오류

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_flutter#56]
4.4.10 버전 업데이트 이후 한 프리셋에서 내부여백, 라운드 등의 수치를 조정하고 다른 프리셋에 들어갈 경우 수치가 동일하게 유지되는 것을 확인하였습니다.

더불어, 설정 후 프리셋 설정에서 나갔다 들어올 경우 모든 수치가 기본 수치로 수정되는 현상을 발견하였습니다.

하나, 실질적인 디자인의 변경은 없어 단순 표기상의 오류로 추정됩니다.

**Comment by n7484443** [comment]
수정하였습니다. 다음 버전에 업데이트 될 예정입니다.
