### ISSUE TITLE
5.0.0 버전 작동 불가 

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_flutter#57]
![image](https://github.com/n7484443/cyoap_flutter/assets/125365947/e306e864-7917-4dfd-a57a-3d283e7388c8)
실행시 회색빛의 화면만 나오고 아무 것도 할 수 없음

**Comment by Ras034** [comment]
실행시 약 0.5초 동안 버전 확인 부분에 버전 인식이 표기되지 않은 상태로 잠깐 화면이 떴다가 회색 화면으로 변함.

**Comment by n7484443** [comment]
수정 완료. 5.0.0-alpha의 -alpha 부분의 파싱 오류 때문. 일단은 그 부분을 제거하였고, 추후 파싱 부분을 개선할 예정
