### ISSUE TITLE
변수 선언관련 오류

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_flutter#59]
프로젝트 설정 이외에 코드만 사용 선택지에서 

var 선택 = false로 설정한 후 
동일 라인 아래 선택지에서 not(선택) 을 선택 조건으로 설정하였을 때 4.4.10 버전에서는 정상작동하는 반면 5.0.5버전에서는 미작동합니다.
[extract_3.zip](https://github.com/n7484443/cyoap_flutter/files/14125130/extract_3.zip)

**Comment by n7484443** [comment]
확인했습니다. 빠른 시일 내로 고치겠습니다.

**Comment by n7484443** [comment]
일반적으로 코드만 사용 기능이 
라인 시작 시의 코드 사용, 라인 끝의 코드 사용
이렇게 두 가지로 사용되는 것으로 알고 있습니다.

현재 라인 끝의 코드 사용은 "라인 종료 시 시행 코드"로 대체되었으니, 보다 깔끔한 코딩(내부적으로나 사용자 측면에서나)을 위해 코드만 사용 기능을 제거하고 "라인 시작 시 시행 코드"로 대체하는 것이 낫다 보여지긴 합니다.

**Comment by n7484443** [comment]
수정 완료. 

추가적으로 일회성 선택지는
not(선택)
로는 안되고

or(not(선택), 본선택지이름)
혹은
or(not(선택), $[본 선택지 이름])
을 사용해야 합니다.
