### ISSUE TITLE
Test sample should take up more space.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#6]
The test sample should take up more space. Right now there is a lot of empty space around it, and when you work in a small window, you get these design errors.
![image](https://user-images.githubusercontent.com/123765425/215984047-41264010-a30b-4198-a647-571f251b8162.png)

**Comment by n7484443** [comment]
Fix 9b957c8fb9537e5736c1094f33a5780a0d70a195
