### ISSUE TITLE
슬라이드 바 추가 제안

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_flutter#60]
현재 선택 방식이 다중선택, 단일 선택으로 제한되어있는데 혹시 
현재 선택지 크기 설정할 때 나오는 슬라이드 바 형식으로도 변수조작이 가능하게 할 수 있을까요.

**Comment by n7484443** [comment]
넵 추가하겠습니다.

**Comment by n7484443** [comment]
아, 이미 있었네요;
다중선택 -> 슬라이더 모드 선택하면 됩니다.
