### ISSUE TITLE
슬라이더 디자인 기능 추가 요청

### ISSUE THREAD

**Issue by Ras034** [n7484443/cyoap_flutter#62]
![image](https://github.com/n7484443/cyoap_flutter/assets/125365947/3c14b5fc-f9f2-4a62-bf3b-0dff5c69e7ca)

해당 사진을 보시면 슬라이더 부분이 주변 디자인과 이질적이게 느껴지는 것을 볼 수 있습니다.
이에 따라서 슬라이더 디자인 파트의 추가를 요청합니다.

**Comment by n7484443** [comment]
[v5.3.8](https://github.com/n7484443/cyoap_flutter/releases/tag/v5.3.8) 에서 추가 완료.
제안 감사합니다.
