### ISSUE TITLE
"lineSetting_tooltip_1" Displayed in the row title.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#7]
'lineSetting_tooltip_1': 'Max %s number of selections'
Now it's just a mistake, but it should be on the right, not in the middle, and not in such a bold font. 
This is visible even in game mode

![Pasted image 20230131231651](https://user-images.githubusercontent.com/123765425/215984729-ce28c12c-770d-4bf1-91b2-e9cd057ff21e.png)

**Comment by n7484443** [comment]
fix - 0813abb7f90dc7729e08bdb8a81e453642d447ae
not perfect, so you can reopen this issue.
