### ISSUE TITLE
ChoiceLine 숨겼을 때 하위 선택지가 결과창에서 사라지는 버그

### ISSUE THREAD

**Issue by NappingOcean** [n7484443/cyoap_flutter#70]
flutter 내에서 플레이했을 때는 나타나지 않으나

vue를 넣은 서버 호스팅 사이트에서는 선택지가 결과창에서 표시되지 않았습니다.

flutter와 vue 중에 어느 것의 버그인지 몰라 이쪽으로 제보드립니다.

**Comment by n7484443** [comment]
[v4.2.7](https://github.com/n7484443/cyoap_vue/releases/tag/v4.2.7) 에서 해당 문제 수정 완료
제보 감사합니다.
