### ISSUE TITLE
There is no way to get the transparent text fill color back.

### ISSUE THREAD

**Issue by DragonsWho** [n7484443/cyoap_flutter#8]
![image](https://user-images.githubusercontent.com/123765425/215986724-9ba8ad83-822d-4cea-8daa-6436a4964ce9.png)

**Comment by n7484443** [comment]
You can use this button
![image](https://user-images.githubusercontent.com/7384324/217645572-54a82cea-0442-42cb-b1a8-88e777444595.png)
